doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'
            rh:
                url: '%env(resolve:DATABASE_RH_URL)%'
        types:
            text_array: "Doctrine\\DBAL\\PostgresTypes\\TextArrayType"
            int_array: "Doctrine\\DBAL\\PostgresTypes\\IntArrayType"
            ts_vector: "Doctrine\\DBAL\\PostgresTypes\\TsvectorType"
            ts_query: "Doctrine\\DBAL\\PostgresTypes\\TsqueryType"
            xml: "Doctrine\\DBAL\\PostgresTypes\\XmlType"
            inet: "Doctrine\\DBAL\\PostgresTypes\\InetType"
            macaddr: "Doctrine\\DBAL\\PostgresTypes\\MacAddrType"

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                auto_mapping: true
                mappings:
                    App:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App
            rh:
                connection: rh
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
